FROM nginx:alpine

# Xóa các file mặc định của Nginx
RUN rm -rf /usr/share/nginx/html/*

# Sao chép các file Flutter Web đã build sẵn từ local vào thư mục phục vụ của Nginx
COPY ./build/web /usr/share/nginx/html

# Ghi đè cấu hình Nginx để hỗ trợ Single Page Application (SPA) Routing của Flutter
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
